### PR TITLE
[WIP] Fn can do hot only, no more cold

### PR DESCRIPTION
**Pull request by denismakogon**
Related to #714

### CODE REVIEW

**Comment by denismakogon** [comment]
Tests are broken so far, mostly because they use the functions that were not designed to be hot.

**Comment by treeder** [comment]
This is obviously something that needs to be discussed bigly before implementing.

**Comment by denismakogon** [comment]
@treeder as far as i understand, there's nothing much to discuss regarding default protocol. The only concern is the number of FDKs we support, so having both HTTP and JSON protocol is more than enough even if you start developing functions with the programming language that is not backed up with FDK we (or someone else) implemented. There would be the certain impact on Fn users, but pre-V1 is the exact time to do so.

**Comment by rdallman** [comment]
yea, wouldn't spend a lot of time on this yet

**Comment by rdallman** [comment]
move discussion to #137 and close this ?

**Pull request closed without merging**
