### PR TITLE
Fixing swagger-doc

### PR DESCRIPTION
**Pull request by denismakogon**
Closes: #439

### CODE REVIEW

**Comment by denismakogon** [comment]
Patch for fn_go: https://github.com/fnproject/fn_go/pull/1 (generated from recent doc)

**Comment by rdallman** [comment]
thanks, i wonder if 'swagger lint' is a thing ?

**Comment by denismakogon** [comment]
I can re-work our client generation script to be a linter.

**Comment by rdallman** [comment]
i was thinking to just lint in CI. i guess a 'dry run' client generation script would do the trick. up to you, not so important. if swagger had something out of the box would be cool to just plug into ci

**Pull request merged**
