### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by hibooboo2**

### CODE REVIEW

**Comment by hibooboo2** [comment]
# CLA BotThank you for your submission!
It appears that the following authors have not signed our Contributor License Agreement:


* [](https://api.github.com/users/hibooboo2)


Please do so now by following [this link](http://www.oracle.com/technetwork/community/oca-486395.html). We are working on modernizing the CLA process into a digital signature but it isn’t quite ready yet.
Once complete, let us know in our [community Slack ](slack.fnproject.io) and we’ll send you an Fn T-shirt.
Thank you for being a part of the Fn Community!

**Comment by hibooboo2** [comment]
# CLA Bot
Thank you for your submission!
It appears that the following authors have not signed our Contributor License Agreement:


* [](https://api.github.com/users/hibooboo2)


Please do so now by following [this link](http://www.oracle.com/technetwork/community/oca-486395.html). We are working on modernizing the CLA process into a digital signature but it isn’t quite ready yet.
Once complete, let us know in our [community Slack ](slack.fnproject.io) and we’ll send you an Fn T-shirt.
Thank you for being a part of the Fn Community!

**Comment by AstromechZA** [comment]
@hibooboo2 The url doesn't seem to resolve for me? Should it rather be http://www.oracle.com/technetwork/community/oca-486395.html or something along those lines?

```
$ dig +noall +ans cla.fnproject.io
$ dig +noall +ans fnproject.io
fnproject.io.		288	IN	A	104.27.147.153
fnproject.io.		288	IN	A	104.27.146.153
```

**Comment by carimura** [comment]
thanks @AstromechZA. PR to fix the URL: https://github.com/fnproject/fn/pull/621

**Pull request merged**
