### PR TITLE
Documenting hybrid mode options

### PR DESCRIPTION
**Pull request by denismakogon**

### CODE REVIEW

**Comment by rdallman** [comment]
do we want to put all hybrid related docs in a separate file? i feel like this will only create confusion for most users that don't want to run hybrid. thanks, we need to doc hybrid stuff (@hhexo has begun, I believe, there is `docs/developers/hybrid.md` to append to possibly)

**Comment by rdallman** [comment]
i foresee 'what's this?' -> 'oh ignore that you don't need it' in slack x10

**Comment by carimura** [comment]
agree with @rdallman on this one... very few customers should be running in Hybrid mode and thus the options are confusing even me.

If we decide to keep them all together there should be a loud "only required in hybrid mode" note on those two options.

**Comment by denismakogon** [comment]
Okay, i'll open issue for extending hybrid doc with all new options.

**Pull request closed without merging**
