### PR TITLE
Added missing -runtime go to fn init

### PR DESCRIPTION
**Pull request by martinahogg**
Fixing fn init command in go tutorial.

### CODE REVIEW

**Comment by rdallman** [comment]
thanks @martinahogg -- did auto-detect runtime not work? if so, will debug that!

**Comment by martinahogg** [comment]
Following the steps in the tutorial exactly, I ran fn init in a empty directory. So there wasn't a func.go for the autodetect to find. So I think this is purely a small issues in the README.md rather than a bug in fn init.

**Comment by rdallman** [comment]
ah, that makes sense. thanks!

**Comment by rdallman** [comment]
I think our tutorials are lacking clarification that one should check out the repo and be in that directory before running them. upon inspection, this tutorial will not build any go files, so the succeeding `fn run` call won't do anything I don't think? was this your experience or did the tutorial seem to work?

**Comment by martinahogg** [comment]
Aaah. I see. I certainly didn't realise I needed to checkout the repo and be in the directory. That would explain why there was no sample.payload.json file too.

I think it would be better if the tutorials could all start from any empty directory and build up from there. This way the person following them knows there's no "magic" going on and they follow every step along the way. 

Thoughts?

**Comment by rdallman** [comment]
lots of tutorial rewriting to be done in that case :) I don't disagree, and it would probably aid learning better, I just think unfortunately most of the ones we have expect the user to checkout the repo. shouldn't be too bad to add disclaimer at top of each README vs having to add more content to each tutorial on how to build all the files necessary.

**Comment by carimura** [comment]
cc @michael-w-williams on this conversation as he's going to be working on tutorial/docs

**Comment by carimura** [comment]
@martinahogg makes sense to build up tutorials from scratch. In fact looks like the state of our tutorials is not great shape -- i guess they got changed... The GoLang one seems overly complicated now, the passing params one doesn't have a README, etc.

@michael-w-williams I'd say next group of work is to go through the whole tutorials series with fresh eyes and document. Include a note at top of readme's specifying to checkout the repo first.

**Comment by michael-w-williams** [comment]
I'll start on it tomorrow.

**Pull request closed without merging**
