### PR TITLE
MISC Remove php example since it is unsupported and not working

### PR DESCRIPTION
**Pull request by tkotosz**
Remove php example tutorial since it is unsupported and the provided code is not working.

### CODE REVIEW

**Comment by tkotosz** [comment]
@rdallman thanks, I forgot about the CLA ... the other repo required it as well... will send the pdf now.

**Comment by delabassee** [comment]
@tkotosz 's OCA has been approved

**Comment by rdallman** [comment]
@tkotosz would you please push a blank commit to kick the cla bot so that we can merge? thank you!

**Comment by tkotosz** [comment]
@rdallman pushed an empty commit and squashed the 2 commits into 1

**Comment by rdallman** [comment]
hey @tkotosz i think if you rebase and squash an empty commit it will just drop it, can you push an empty commit and leave it please? I think the cla bot won't run until it gets another commit with an email address to check. appreciate the housekeeping - we squash on merge as well, so not a big deal here hygiene wise.

**Comment by tkotosz** [comment]
@rdallman it seems the CLA bot approved the PR :)

**Comment by rdallman** [comment]
sweet, the thing is a little slow. thank you

**Pull request merged**
