### PR TITLE
Update for trivial typo

### PR DESCRIPTION
**Pull request by topiaruss**

### CODE REVIEW

**Comment by hibooboo2** [comment]
# Oracle CLA Bot
	Thank you for your submission, we really appreciate it. Like many open source projects,
	we ask that you sign our [Contributor License Agreement](http://www.oracle.com/technetwork/community/oca-486395.html) before we can accept your contribution.
	
- @topiaruss

**Comment by hibooboo2** [comment]
# Oracle CLA Bot
	Thank you for your submission, we really appreciate it. Like many open source projects,
	we ask that you sign our [Contributor License Agreement](http://www.oracle.com/technetwork/community/oca-486395.html) before we can accept your contribution.
	
- @topiaruss

**Comment by topiaruss** [comment]
CLA signed and emailed, per instructions

**Comment by hibooboo2** [comment]
# CLA BotThank you for your submission!
It appears that the following authors have not signed our Contributor License Agreement:


* [](https://api.github.com/users/topiaruss)


Please do so now by following [this link](http://www.oracle.com/technetwork/community/oca-486395.html). We are working on modernizing the CLA process into a digital signature but it isn’t quite ready yet.
Once complete, let us know in our [community Slack ](slack.fnproject.io) and we’ll send you an Fn T-shirt.
Thank you for being a part of the Fn Community!

**Comment by hibooboo2** [comment]
# CLA Bot
Thank you for your submission!
It appears that the following authors have not signed our Contributor License Agreement:


* [](https://api.github.com/users/topiaruss)


Please do so now by following [this link](http://www.oracle.com/technetwork/community/oca-486395.html). We are working on modernizing the CLA process into a digital signature but it isn’t quite ready yet.
Once complete, let us know in our [community Slack ](slack.fnproject.io) and we’ll send you an Fn T-shirt.
Thank you for being a part of the Fn Community!

**Comment by carimura** [comment]
thanks @topiaruss -- we'll look for it ASAP and clear this check!

Thanks!

**Comment by rdallman** [comment]
bump @carimura for cla bot (merge is blocked)

**Comment by rdallman** [comment]
this is merged into mainline via another patch, thanks!

**Comment by topiaruss** [comment]
NP.


Russ Ferriday
CEO Topia Systems Ltd.
topiaruss@gmail.com
+44 7429 518822

**Pull request closed without merging**
