### PR TITLE
Adding Fn invoke endpoint that works just like triggers endpoint

### PR DESCRIPTION
**Pull request by mantree**
A version of Fn invoke that works exactly like the trigger endpoint point.

### CODE REVIEW

**Comment by rdallman** [comment]
think i get the basic idea here, do the same thing as triggers api but without the trigger configuration bits. that line of reasoning is sensible i think for interfacing with the agent to get something working, in the interest of looking forward is it a lot of work for us to restrict the domain of the http API to only accept cloud events? is the cloudevent library unworkable hence resurrecting the event logic from earlier https://github.com/fnproject/fn/pull/1165 ?

(will fiddle with this today)

**Comment by rdallman** [comment]
i guess part of this exercise was to scope out exactly what that might look like exactly, we're just now trying to skip doing that to have something working is what it seems like.

**Comment by skinowski** [comment]
Why is the resource in models only have Memory?

**Comment by mantree** [comment]
@skinowski that and timeout are going to be the only configurables, i think shapes are going to come into this area.

**Comment by rdallman** [comment]
> Why is the resource in models only have Memory?

good catch, yea we need to iron that out

**Pull request merged**
