### PR TITLE
fn: clean api tests: removed multi log

### PR DESCRIPTION
**Pull request by skinowski**
*) fn-test-utils covers multi-log case, with sleep in between.
*) added trailer data to fn-test-utils (going to be useful for large response tests)
*) added logging to panic/error cases in fn-test-utils.

### CODE REVIEW

**Comment by skinowski** [comment]
Fixes: #796

**Comment by rdallman** [comment]
a quick glance at this has me curious whether our turning off of the docker logs and using async attach is the race, and not a poorly built multi log image (though i look forward to removing this image, i can't imagine it's doing anything that crazy). to be clear: want to move forward with this, and thanks for doing it; just got me thinking about the root of the issue since when it happens it seems to skip the first line and it seems pursuant to a log race.

**Comment by skinowski** [comment]
Another reason why I really want to remove the cold-impl... Hot has hostWriter in stderr, but cold doesn't.. The test case only tests cold...

**Comment by rdallman** [comment]
i think the race exists but is more far-fetched for hot. if attach takes longer than start + hand out of slot, then we can miss logs. attach is done in parallel to that, so it could happen. previously, we streamed all logs up to attach time, which prevented this bug. it seems like we just need to add synchronous attachment to the container and add our own goroutine that we can manage so that we can properly manage the logs (it's very much worth turning off the json logs).

**Comment by rdallman** [comment]
in any event, we can do that separately (can file another issue)

**Comment by skinowski** [comment]
Raising it to 3 secs triggered it now, but only for hot, cold passed. Arrghh. I'll merge this and we can work on the runner test instead of api tests.

**Comment by skinowski** [comment]
Nevermind, it's off/on, seems random...

**Comment by rdallman** [comment]
yea, i think it's just racy, multi log test waffled back and forth

**Comment by skinowski** [comment]
I'll take a closer look tomorrow at this...

**Pull request merged**
