### PR TITLE
Removed a bunch of old examples.

### PR DESCRIPTION
**Pull request by treeder**

### CODE REVIEW

**Comment by carimura** [comment]
nice. looks good.

**Comment by nigeldeakin** [comment]
What's your intention in renaming  `fn/examples/grafana` to `fn/examples/UPDATE-OR-DELETE/grafana`? I added this recently, and have a PR open to update it.

**Comment by treeder** [comment]
No intention, thought it was old. I'll move it back. Although that looks like something that would be better in the docs, rather than examples. Examples are for example functions.

**Comment by treeder** [comment]
Moved it back @nigeldeakin

**Pull request merged**
