### PR TITLE
fn: swagger update for tmpfs size

### PR DESCRIPTION
**Pull request by skinowski**

### CODE REVIEW

**Comment by rdallman** [comment]
same question as in #1030 -- long term viability / desire of this as a feature was left murky

**Comment by skinowski** [comment]
Let's hold off on this one... Until config/operational config decision is finalized.

**Comment by skinowski** [comment]
@shaunsmith was asking about documentation.

**Comment by zootalures** [comment]
We're going to remove user configuration this  and CPU configuration from the APIs in the trigger change -  as discussed previously it's unlikely that honoring these by guarantee (without adding substantial complexity to scheduling) will work in a scaled up system .  For both we'll set these by configuration in the server as a function of memory initially .

**Comment by rdallman** [comment]
wrote that up (at last) https://github.com/fnproject/fn/issues/1106 i'm not sure it was well circulated that it was planned in triggers changes, feel free to add [0.2] to title or 'waiting' tag depending on scope

**Comment by skinowski** [comment]
Sounds good. This PR was a consistency change to keep route configuration: cpu/mem/tmpfssize together. Since tmpfssize was merged in already, it should be in swagger. When we remove it, we can remove it along with cpu, etc.

**Pull request merged**
