### PR TITLE
Update k8s docs

### PR DESCRIPTION
**Pull request by eric4545**

### CODE REVIEW

**Comment by denismakogon** [comment]
@derekschultz

**Comment by derekschultz** [comment]
LGTM, but holding off on merge until we have CLA in place.

**Comment by hibooboo2** [comment]
# Oracle CLA Bot
	Thank you for your submission, we really appreciate it. Like many open source projects,
	we ask that you sign our [Contributor License Agreement](http://www.oracle.com/technetwork/community/oca-486395.html) before we can accept your contribution.
	
- @eric4545

**Comment by hibooboo2** [comment]
# Oracle CLA Bot
	Thank you for your submission, we really appreciate it. Like many open source projects,
	we ask that you sign our [Contributor License Agreement](http://www.oracle.com/technetwork/community/oca-486395.html) before we can accept your contribution.
	
- @eric4545

**Comment by hibooboo2** [comment]
# CLA BotThank you for your submission!
It appears that the following authors have not signed our Contributor License Agreement:


* [](https://api.github.com/users/eric4545)


Please do so now by following [this link](http://www.oracle.com/technetwork/community/oca-486395.html). We are working on modernizing the CLA process into a digital signature but it isn’t quite ready yet.
Once complete, let us know in our [community Slack ](slack.fnproject.io) and we’ll send you an Fn T-shirt.
Thank you for being a part of the Fn Community!

**Comment by hibooboo2** [comment]
# CLA Bot
Thank you for your submission!
It appears that the following authors have not signed our Contributor License Agreement:


* [](https://api.github.com/users/eric4545)


Please do so now by following [this link](http://www.oracle.com/technetwork/community/oca-486395.html). We are working on modernizing the CLA process into a digital signature but it isn’t quite ready yet.
Once complete, let us know in our [community Slack ](slack.fnproject.io) and we’ll send you an Fn T-shirt.
Thank you for being a part of the Fn Community!

**Comment by eric4545** [comment]
Fix already made on master, close PR.

**Pull request closed without merging**
