### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by making**

### CODE REVIEW

**Comment by rdallman** [comment]
thanks! we'll make CI work for forks now :) -- working on this

**Comment by treeder** [comment]
Thanks for the PR, but we need to get a CLA in place so can't merge this quite yet... :( I made the change though since it's important, looks like it was from a search and replace operation.

**Comment by making** [comment]
How to sign CLA is not ready, right?
https://github.com/fnproject/fn/blob/master/CONTRIBUTING.md

I don't mind if you close this PR and fix directly (it's just one character :))

**Comment by treeder** [comment]
@making it's not quite ready yet (the CLA), should be up in the next couple of days.

**Pull request closed without merging**
