### PR TITLE
Logs should support specifying region when using S3-compatible object store 

### PR DESCRIPTION
**Pull request by gviedma**
Fixes issue #644

### CODE REVIEW

**Comment by msgodf** [comment]
LGTM. Does it work? :)

**Comment by msgodf** [comment]
Looks like the existing tests for this are out of date, as they only run if the `MINIO_URL` environment variable is set.

**Comment by msgodf** [comment]
Also, might be worth noting that this is part of the work for 
https://github.com/fnproject/internal/issues/34

**Comment by rdallman** [comment]
> Looks like the existing tests for this are out of date, as they only run if the MINIO_URL environment variable is set.

the test script sets this up properly https://github.com/fnproject/fn/blob/master/test.sh#L25 so the tests will run against minio. we can run minio locally so it seems the best way to test, and the tests pass here so I think it works.

@gviedma you need to make the oracle org public on github to auto pass the CLA bot, or alternatively signing the CLA should work too but it's slightly more involved.

**Comment by gviedma** [comment]
I've tested running some calls against Oracle Object Store and uploading of log files is currently failing. It seems that OSS requires the actual content length to be provided with the request. I'll investigate further.

**Comment by rdallman** [comment]
makes sense. we should be able to provide that relatively easily. somewhat related: https://github.com/fnproject/fn/issues/646 (I believe in progress atm)

**Pull request merged**
