### PR TITLE
update fsouza to v1.2.0

### PR DESCRIPTION
**Pull request by rdallman**
- What I did

updates fsouza in order to get `identityToken`

- How I did it

`dep ensure` after changing Gopkg.toml rev for `fsouza/go-dockerclient`

- How to verify it

ci pass?

- One line description for the changelog

update deps

### CODE REVIEW

**Comment by rdallman** [comment]
mmm, docker issues. debugging.

**Comment by rdallman** [comment]
we're requiring go1.7 at build time already (same reason) https://github.com/fnproject/fn/blob/master/api/agent/drivers/docker/docker_client.go#L1

**Comment by rdallman** [comment]
thanks for review

**Comment by srpurani** [comment]
@rdallman I still don't see identityToken in AuthConfiguration here https://github.com/fnproject/fn/blob/master/vendor/github.com/fsouza/go-dockerclient/auth.go

**Pull request merged**
