### PR TITLE
Fix some typos in README

### PR DESCRIPTION
**Pull request by lagartoflojo**

### CODE REVIEW

**Comment by treeder** [comment]
Thanks, we have to wait to get our CLA in place, will merge right after.

**Comment by hibooboo2** [comment]
# Oracle CLA Bot
	Thank you for your submission, we really appreciate it. Like many open source projects,
	we ask that you sign our [Contributor License Agreement](http://www.oracle.com/technetwork/community/oca-486395.html) before we can accept your contribution.
	
- @lagartoflojo

**Comment by hibooboo2** [comment]
# Oracle CLA Bot
	Thank you for your submission, we really appreciate it. Like many open source projects,
	we ask that you sign our [Contributor License Agreement](http://www.oracle.com/technetwork/community/oca-486395.html) before we can accept your contribution.
	
- @lagartoflojo

**Comment by lagartoflojo** [comment]
Hi, from the linked page:

> Submitting the OCA procedure
> 1.  Download the OCA from here: http://www.oracle.com/technetwork/oca-405177.pdf
> 2.  Print it
> 3.  Fill out and sign the form (do not forget to fill in the point 7 and provide your mailing address not only your e-mail address)
> 4.  Scan the paper
> 5.  Send a picture/PDF to oracle-ca_us [at] oracle [dot] com

Really?? It's gonna take me longer to do this than it took me to create the PR...
You are welcome to open a new PR with the typo fixes. I'll close this.
I'll consider following the CLA procedure if I ever contribute something more significant to the project.

**Comment by carimura** [comment]
hi @lagartoflojo thanks for the PR and feedback! We're definitely aware and working on modernizing the process into a digital signature.

**Pull request closed without merging**
