### PR TITLE
WIP: Adding system tests

### PR DESCRIPTION
**Pull request by reclaro**
System tests for hot call functions in json and http format

### CODE REVIEW

**Comment by reclaro** [comment]
This is a WIP change at the moment, the tests are failing as I don't have pushed the two new images used in system tests.

**Comment by rdallman** [comment]
@reclaro still WIP here ?

**Comment by skinowski** [comment]
@reclaro there's ./images/fn-test-utils already, so I think you can just use that if that's easier. There's some examples on how to use it in runner_tests.go. Makefile already builds/prepares fn-test-utils, so it'll be faster and you don't need to do anything to build/pull it. See:

https://github.com/fnproject/fn/tree/master/images/fn-test-utils

**Comment by reclaro** [comment]
@rdallman I am not working  on it right now I might have some time in the future no ETA at the moment, is that ok for you?

**Comment by rdallman** [comment]
no worries - up to you, can leave it open if it's still wip

**Comment by zootalures** [comment]
CLosing as we deleted the system tests.

**Pull request closed without merging**
