### PR TITLE
if a slot is available, don't launch more

### PR DESCRIPTION
**Pull request by rdallman**
since we were sending a signal before checking if a slot was available, even
in the case of serial calls locally I was seeing 2 containers launch. if we
only send a signal after first checking if a slot is available, this goes
away. 1 usec should not be too offensive of an additional wait, all things
considered here.

### CODE REVIEW

**Comment by skinowski** [comment]
hmm, I have some doubts about this. hotLauncher missing signals...

**Comment by rdallman** [comment]
it will definitely not send as many signals, which yea it appears that the hot launcher routine relies on this to know that requests have come in for a route to not die, and if you e.g. run serial for 1 hour then the launcher will die. 

will look into it, good catch

**Comment by skinowski** [comment]
I think this PR if fine, I'm just thinking if we need to tune isNewContainer needed instead...

**Comment by skinowski** [comment]
Could you post the logs from that serial run if you have it, if not no worries...

**Comment by skinowski** [comment]
ok, this is probably fine (and needed) since:

1) missing signals are not bad, since hot launcher checks if slot is in use before deletion/exit
2) https://github.com/skinowski/fn/blob/master/api/agent/slots.go#L216 probably is the root cause, but this change makes this over shoot estimate better IMHO.

**Comment by rdallman** [comment]
i have a test in a branch where i get it to crop up consistently, i've cut it off to a branch [here](https://github.com/fnproject/fn/compare/double-launch-button?expand=1#diff-b59019a3973054d1355bcb50d9f7202dR476) -- i would say ignore the test failure and other code changes, it's very much a WIP -- but the code runs and you can cut it out into a clean branch if you'd like. i made a note to make that test ensure that only one container gets launched (I will try to do this, have not investigated plumbing depths). 

if you examine the output for the linked test you'll see output akin to:

```
INFO[2018-01-18T01:21:59-08:00] available memory                              availMemory=3341485671 cgroupLimit=9223372036854771712 headRoom=371276185 totalMemory=3712761856
INFO[2018-01-18T01:21:59-08:00] sync and async ram reservations               ramAsync=2673188537 ramAsyncHWMark=2138550829 ramSync=668297134
INFO[2018-01-18T01:21:59-08:00] available cpu                                 availCPU=1000 totalCPU=1000
INFO[2018-01-18T01:21:59-08:00] sync and async cpu reservations               cpuAsync=800 cpuAsyncHWMark=640 cpuSync=200
WARN[2018-01-18T01:21:59-08:00] Severaly Limited CPU: cpuAsync < 1000m (1 CPU) 
INFO[2018-01-18T01:21:59-08:00] Hot function launcher starting                app=myapp id=01C4496C2S0000600000000000 launcher_timeout=1h0m0s route=/sleeper
DEBU[2018-01-18T01:21:59-08:00] Hot function launcher stats                   app=myapp currentStats="{[0 0 1] [0 0 0] [0 0 0]}" id=01C4496C2S0000600000000000 previousStats="{[0 0 1] [0 0 0] [0 0 0]}" route=/sleeper
INFO[2018-01-18T01:21:59-08:00] Hot function launcher starting hot container  app=myapp currentStats="{[0 0 1] [0 0 0] [0 0 0]}" id=01C4496C2S0000600000000000 previousStats="{[0 0 1] [0 0 0] [0 0 0]}" route=/sleeper
DEBU[2018-01-18T01:21:59-08:00] Starting container execution                  app=myapp container=01C4496C2T0000800000000000 cpus= format=http id=01C4496C2T0000800000000000 idle_timeout=60 image=fnproject/fn-test-utils memory=256 route=/sleeper
DEBU[2018-01-18T01:21:59-08:00] Hot function launcher stats                   app=myapp currentStats="{[0 1 1] [0 0 0] [0 0 0]}" id=01C4496C2S0000600000000000 previousStats="{[0 1 1] [0 0 0] [0 0 0]}" route=/sleeper
INFO[2018-01-18T01:21:59-08:00] starting call                                 app=myapp container_id=01C4496C2T0000800000000000 id=01C4496C2S0000600000000000 route=/sleeper
SWAP READER *io.PipeReader 0xc42000ee50 
DEBU[2018-01-18T01:22:03-08:00] Hot function launcher stats                   app=myapp currentStats="{[1 0 1] [1 1 1] [0 0 0]}" id=01C4496C2S0000600000000000 previousStats="{[1 0 1] [1 1 1] [0 0 0]}" route=/sleeper
INFO[2018-01-18T01:22:03-08:00] Hot function launcher starting hot container  app=myapp currentStats="{[1 0 1] [1 1 1] [0 0 0]}" id=01C4496C2S0000600000000000 previousStats="{[1 0 1] [1 1 1] [0 0 0]}" route=/sleeper
SWAP READER *agent.waitReader 0x1a678a8 
INFO[2018-01-18T01:22:03-08:00] starting call                                 app=myapp container_id=01C4496C2T0000800000000000 id=01C4496FZT0000A00000000000 route=/sleeper
SWAP READER *io.PipeReader 0xc42000eec0 
DEBU[2018-01-18T01:22:03-08:00] Starting container execution                  app=myapp container=01C4496FZV0000C00000000000 cpus= format=http id=01C4496FZV0000C00000000000 idle_timeout=60 image=fnproject/fn-test-utils memory=256 route=/sleeper
INFO[2018-01-18T01:22:03-08:00] hot function terminated                       app=myapp cpus= error="<nil>" format=http id=01C4496C2T0000800000000000 idle_timeout=60 image=fnproject/fn-test-utils memory=256 route=/sleeper
SWAP READER *agent.waitReader 0x1a678a8 
INFO[2018-01-18T01:22:07-08:00] hot function terminated                       app=myapp cpus= error="<nil>" format=http id=01C4496FZV0000C00000000000 idle_timeout=60 image=fnproject/fn-test-utils memory=256 route=/sleeper
```

when from the test it's apparent that tasks are being ran sequentially. i have confirmed that after these changes from #701 land, only 1 container gets launched.

**Comment by rdallman** [comment]
> ok, this is probably fine (and needed) since:

roger. big green button ?

**Comment by skinowski** [comment]
I pressed it. :-)

**Comment by skinowski** [comment]
hmm, note to self, looks like slots may need one more metric. We've got 'running', 'starting', 'waiting' states, but we need something that distinguishes if those running containers are idle or not.

**Pull request merged**
