### PR TITLE
Fnlb was moved to its own repo: fnproject/lb

### PR DESCRIPTION
**Pull request by denismakogon**
https://github.com/fnproject/lb

Closes: #555

### CODE REVIEW

**Comment by rdallman** [comment]
and the ebb of the mono repo goes out... one day to flow right back in... :)

**Comment by rdallman** [comment]
yea, this https://github.com/fnproject/fn/blob/master/release.sh#L51 good catch -- i grepped for `fnlb` and everything else looks innocuous

**Comment by rdallman** [comment]
oh, there's a test harness that should be moved, too. everything else is innocuous*

**Comment by rdallman** [comment]
can't link to frickin readme lines (wth github, it renders in markdown only) but there's also a link in the readme

**Comment by denismakogon** [comment]
Weird things are happening, newer our docker client can't talk to docker somehow. I filed an issue against docker client we use: https://github.com/fsouza/go-dockerclient/issues/705

**Comment by rdallman** [comment]
thanks. we could lock that version of the docker client to vendor until your update comes in, and then proceed here without any changes necessary to the docker driver.

**Comment by denismakogon** [comment]
@rdallman was able to lock the docker client version and get newer deps, so the code works fine without any changes.

**Pull request merged**
