### PR TITLE
watch the writer to not double write

### PR DESCRIPTION
**Pull request by rdallman**
we're writing our error over a previously perfectly fine response from a call.
we need to just not do that. i didn't test the more exotic cases, this should
do the trick.

related to #326 but doesn't close entirely (just one case mentioned)

### CODE REVIEW

**Comment by rdallman** [comment]
i think this will fix this one https://github.com/fnproject/fn/issues/326#issuecomment-355665645 -- i gotta run for today, should do the trick though. i can/should/will test more thoroughly (a testing on the case linked would be nice to confirm)

**Comment by treeder** [comment]
This doesn't fix 326, it possibly makes it worse because now we're hiding the fact that the function failed even more. 

Needs to return a 500 and an error response if the function fails at any point.

**Comment by treeder** [comment]
This example https://github.com/fnproject/fn/issues/326#issuecomment-355665645 output is very contrived btw, I threw in a panic at the end. That wouldn't be typical.

**Comment by rdallman** [comment]
> This example #326 (comment) output is very contrived btw, I threw in a panic at the end. That wouldn't be typical.

ok, think this confused my interpretation of what was happening then.

**Pull request closed without merging**
